spring:
  application:
    name: diabetes-assessment-service

server:
  port: 8083

jwt:
  secret: 94a2b5be43204b928b31c8a1aa29bc98afac9e4b3d1e4e0c8522e4ec21767914

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

patient:
  url: http://gateway-service:8080/api/patients

note:
  url: http://gateway-service:8080/api/notes

logging:
  level:
    org.springframework.web: DEBUG
    com.oc_p9.diabetes_assessment: DEBUG
