services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017

  patient-service:
    build: ./patient-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  gateway:
    build: ./gateway
    ports:
      - "8090:8090"
