services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=medilabo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - medilabosolutions-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootroot"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:6.0
    container_name: medilabo-mongo-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: notedb
    volumes:
      - ./note-service/initdb:/docker-entrypoint-initdb.d:ro
      - mongo-data:/data/db
    networks:
      - medilabosolutions-net
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          mongosh -u root -p rootroot --authenticationDatabase admin
          --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  patient-service:
    build:
      context: ./patient-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - medilabosolutions-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  note-service:
    build:
      context: ./note-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_ROOT=root
      - MONGO_PASS=rootroot
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - medilabosolutions-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  diabetes-assessment-service:
    build:
      context: ./diabetes-assessment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      patient-service:
        condition: service_healthy
      note-service:
        condition: service_healthy
    networks:
      - medilabosolutions-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      patient-service:
        condition: service_healthy
      note-service:
        condition: service_healthy
      diabetes-assessment-service:
        condition: service_healthy
    networks:
      - medilabosolutions-net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  front-service:
    build:
      context: ./front-service/angular-diabetes-app
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      gateway-service:
        condition: service_healthy
    networks:
      - medilabosolutions-net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

volumes:
  mysql-data:
  mongo-data:

networks:
  medilabosolutions-net:
    driver: bridge
