spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:8085"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: patient
          uri: http://patient-service:8081
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=0

        - id: note
          uri: http://note-service:8082
          predicates:
            - Path=/api/notes/**
          filters:
            - StripPrefix=0

        - id: diabetes
          uri: http://diabetes-assessment-service:8083
          predicates:
            - Path=/api/assessments/**
          filters:
            - StripPrefix=0

server:
  port: 8080

jwt:
  secret: 94a2b5be43204b928b31c8a1aa29bc98afac9e4b3d1e4e0c8522e4ec21767914

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
