spring:
  application:
    name: note-service
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb://root:rootroot@mongo:27017/notedb?authSource=admin&serverSelectionTimeoutMS=50000

server:
  port: 8082

jwt:
  secret: 94a2b5be43204b928b31c8a1aa29bc98afac9e4b3d1e4e0c8522e4ec21767914

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
